### ISSUE TITLE
About console.log-ing

### ISSUE THREAD

**Issue by shanemac10** [M-Schwiesow/teamroster#2]
For example here...
```
  getGame: function(req,res) {
    console.log("getGame found");
    Game.findById({_id: req.params.id}, function(err, game){
      if(err){
        res.send(err);
      } else {
        res.json(game);
      }
    });
  }
```
I might do something along the lines of...
```  
getGame: function(req,res) {
    console.log("games.getGame() req.params:", req.params);
    Game.findById({_id: req.params.id}, function(err, game){
      if(err){
        console.error("games.getGame ERROR:", err);
        res.send(err);
      } else {
        console.log("games.getGame game:", game);
        res.json(game);
      }
    });
  }
```
Stuff like this will let you see whats happening where. Keep the logs unique, understandable, and valuable. If you were having a REALLY tough time, you can log req itself, but that is a large object. If you have really large objects, the logging functionality will sometimes only display one level deep in a big object. Meaning it might say "... params: [Object object]..." instead of printing out the whole thing. You can log just the object variable with NO strings or anything else added in, or use %j for JSON (it's kinda like using the json pipe Angular html templates i.e. {{ myObject | json }}) 

Here are examples...
```
console.log("games.getGame() req :");
console.log(req);  // dedicated log for the object
OR
console.log("games.getGame() req: %j", req);
```

https://github.com/M-Schwiesow/teamroster/blob/64442ea6d0298e2c5363dfec288c02bb436c92e8/server/controllers/games.js#L16

**Comment by M-Schwiesow** [comment]
I have logged req itself before, it is a large object.  The JSON modifier is a really neat/useful trick, I'm going to have to try that out.  Before I was done fretting over the routes I wound up placing this at the start of my routing:
`app.all('*', function(req,res,next){`
`console.log("Incoming request information:"); `
`console.log("req.method: ",req.method);     `
`console.log("req.originalUrl: ",req.originalUrl); `
`console.log("req.params: ",req.params); `
`console.log("req.body: ",req.body); `
`console.log("req.rawHeaders: ",req.rawHeaders); `
`console.log("*******endlog*********"); `
`next(); `
`});`
I still had to place logs in my methods to see where and when they were firing, but that captured everything I could see as useful about all my incoming requests.  This was helpful in my scenario because it was the best confirmation I had that my client side simply wasn't sending a request of any sort on my delete methods.
My logging tends to get more detailed the deeper into an issue I get; most of the time I start with very simple "I am here" kind of logs.  I need to break that habit and type the 10 extra characters to start -_-
